### ISSUE TITLE
Calling custom extensions using trainer

### ISSUE THREAD

**Issue by MannyKayy** [pfnet/chainermn#73]
I have a custom extension that changes the learning rate after a certain number of epochs.
This extension is called via a lambda function in the trainer 'observe value' extension, as shown below:

`trainer.extend(extensions.observe_value('lr', lambda _: lr_shift()), trigger=(150, 'epoch'))`

I am wondering if this extension should be called by a single work or by all the workers?

e.g. should it be..
`if comm.rank == 0:
             trainer.extend(extensions.observe_value('lr', lambda _: lr_shift()), trigger=(150, 'epoch'))`
`

Thanks

**Comment by iwiwi** [comment]
Call it from all workers, please.
